spring:
    jpa:
        hibernate:
            ddl-auto:update
    datasource:
        url:jdbc:mysql://182.61.45.76:63306/user
        username:zhangming
        password:zm@474577048
        driver-class-name:com.mysql.jdbc.Driver
eureka:
    instance:
        preferIpAddress:true
    client:
        registerWithEureka:true
        fetchRegistry:true
        serviceUrl:
            defaultZone:http://182.61.45.76:8070/eureka/